# 일단 데이터 한번 가져와보기

`yfinance` 라이브러리를 이용하여 가져와보겠습니다.

### `yfinance`가 제공하는 기능
- Ticker
- Tickers (?)
- download
- search
- WebSocket
- Screener

### 제공하는 데이터
- 단일종목
- 여러종목
- 검색
- 실시간 스트리밍

> 공식 인증이나 Yahoo와 제휴된 도구가 아니라 조심히 써야함.

In [2]:
import yfinance as yf

df = yf.download("NVDA", start="2020-01-01", end="2026-01-01")

print(df.head())
print(df.info())

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open     Volume
Ticker          NVDA      NVDA      NVDA      NVDA       NVDA
2020-01-02  5.970754  5.970754  5.891363  5.941884  237536000
2020-01-03  5.875186  5.918988  5.826158  5.851045  205384000
2020-01-06  5.899826  5.905052  5.755727  5.781859  262636000
2020-01-07  5.971251  6.017044  5.883150  5.928196  314856000
2020-01-08  5.982451  6.023765  5.926952  5.967021  277108000
<class 'pandas.DataFrame'>
DatetimeIndex: 1508 entries, 2020-01-02 to 2025-12-31
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, NVDA)   1508 non-null   float64
 1   (High, NVDA)    1508 non-null   float64
 2   (Low, NVDA)     1508 non-null   float64
 3   (Open, NVDA)    1508 non-null   float64
 4   (Volume, NVDA)  1508 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 70.7 KB
None

# 티커 받고싶어서 `finance-datareader` 라이브러리 받음

In [2]:
import FinanceDataReader as fdr

nasdaq = fdr.StockListing("NASDAQ")
# print(nasdaq.head())

semiconductor_mask = nasdaq["Industry"] == "반도체"

# print(nasdaq[])

100%|██████████| 3892/3892 [00:06<00:00, 565.84it/s]

In [4]:
print(nasdaq[semiconductor_mask])

     Symbol                              Name IndustryCode Industry
0      NVDA                       NVIDIA Corp     57101010      반도체
6      AVGO                      Broadcom Inc     57101010      반도체
9        MU             Micron Technology Inc     57101010      반도체
11      AMD        Advanced Micro Devices Inc     57101010      반도체
13     INTC                        Intel Corp     57101010      반도체
...     ...                               ...          ...      ...
3279   PRSO                        Peraso Inc     57101010      반도체
3320   EBON  Ebang International Holdings Inc     57101010      반도체
3354   SELX         Semilux International Ltd     57101010      반도체
3529   SMTK                      SmartKem Inc     57101010      반도체
3560   DAIC                    CID HoldCo Inc     57101010      반도체

[75 rows x 4 columns]

In [11]:
import pandas as pd

print((nasdaq[semiconductor_mask]["Symbol"] == "MU").sum())

print(nasdaq[nasdaq["Symbol"].eq("MU")])

1
  Symbol                   Name IndustryCode Industry
9     MU  Micron Technology Inc     57101010      반도체

In [21]:
# print(nasdaq)

# print(etf_df.info())

nvda_df = fdr.DataReader(nasdaq[semiconductor_mask]["Symbol"][0])

In [22]:
nvda_df

,Open,High,Low,Close,Volume,Adj Close
1999-01-22,0.043750,0.048828,0.038802,0.041016,2714688000,0.037603
1999-01-25,0.044271,0.045833,0.041016,0.045313,510480000,0.041542
1999-01-26,0.045833,0.046745,0.041146,0.041797,343200000,0.038319
1999-01-27,0.041927,0.042969,0.039583,0.041667,244368000,0.038200
1999-01-28,0.041667,0.041927,0.041276,0.041536,227520000,0.038080
...,...,...,...,...,...,...
2026-05-20,223.179993,226.130005,220.500000,223.470001,184201600,223.470001
2026-05-21,222.289993,227.399994,217.929993,219.509995,203381800,219.509995
2026-05-22,220.899994,221.009995,214.800003,215.330002,169275700,215.330002
2026-05-26,216.539993,218.179993,212.000000,214.860001,187202600,214.860001
2026-05-27,214.119995,214.139999,208.779999,212.600006,161326568,212.600006

In [44]:
# nvda_df["change"] = pd.concat([nvda_df["Close"], pd.Series([0])], ignore_index=True) - pd.concat([pd.Series([0]) ,nvda_df["Close"]], ignore_index=True) 

# nvda_df["Close"]
nvda_df["change"] = pd.concat([pd.Series([0]) ,nvda_df["Close"]], ignore_index=True) - pd.concat([nvda_df["Close"], pd.Series([0])], ignore_index=True)[0:6879]

In [46]:
nvda_df

,Open,High,Low,Close,Volume,Adj Close,change
1999-01-22,0.043750,0.048828,0.038802,0.041016,2714688000,0.037603,NaN
1999-01-25,0.044271,0.045833,0.041016,0.045313,510480000,0.041542,NaN
1999-01-26,0.045833,0.046745,0.041146,0.041797,343200000,0.038319,NaN
1999-01-27,0.041927,0.042969,0.039583,0.041667,244368000,0.038200,NaN
1999-01-28,0.041667,0.041927,0.041276,0.041536,227520000,0.038080,NaN
...,...,...,...,...,...,...,...
2026-05-20,223.179993,226.130005,220.500000,223.470001,184201600,223.470001,NaN
2026-05-21,222.289993,227.399994,217.929993,219.509995,203381800,219.509995,NaN
2026-05-22,220.899994,221.009995,214.800003,215.330002,169275700,215.330002,NaN
2026-05-26,216.539993,218.179993,212.000000,214.860001,187202600,214.860001,NaN
2026-05-27,214.119995,214.139999,208.779999,212.600006,161326568,212.600006,NaN

In [48]:
nvda_df["change"] = nvda_df["Close"].diff().fillna(0)

In [49]:
nvda_df

,Open,High,Low,Close,Volume,Adj Close,change
1999-01-22,0.043750,0.048828,0.038802,0.041016,2714688000,0.037603,0.000000
1999-01-25,0.044271,0.045833,0.041016,0.045313,510480000,0.041542,0.004297
1999-01-26,0.045833,0.046745,0.041146,0.041797,343200000,0.038319,-0.003516
1999-01-27,0.041927,0.042969,0.039583,0.041667,244368000,0.038200,-0.000130
1999-01-28,0.041667,0.041927,0.041276,0.041536,227520000,0.038080,-0.000131
...,...,...,...,...,...,...,...
2026-05-20,223.179993,226.130005,220.500000,223.470001,184201600,223.470001,2.860001
2026-05-21,222.289993,227.399994,217.929993,219.509995,203381800,219.509995,-3.960007
2026-05-22,220.899994,221.009995,214.800003,215.330002,169275700,215.330002,-4.179993
2026-05-26,216.539993,218.179993,212.000000,214.860001,187202600,214.860001,-0.470001
2026-05-27,214.119995,214.139999,208.779999,212.600006,161326568,212.600006,-2.259995