[노션 노트정리](https://app.notion.com/p/3ea117a41d4d80f28d35c078ea161ecf?source=copy_link)

# **1. 자연어 처리 기초**

## 1. 자연어
자연어는 인간이 일상적으로 의사소통에 사용하는 언어로, 말과 글을 통해 표현되는 언어를 말합니다.

자연어는 문법, 어휘, 맥락, 뉘앙스 등 복잡한 요소들로 이루어져 있어 규칙적인 구조와 함께 다양한 변형이 가능합니다.

컴퓨터 과학에서는 이러한 자연어를 이해하고 처리하기 위해 자연어 처리(NLP, Natural Language Processing) 기술이 사용되며, 이를 통해 텍스트 분석, 번역, 음성 인식, 챗봇과 같은 다양한 응용이 가능합니다.

자연어는 인간의 사고와 문화적 배경을 반영하므로, 이를 다루는 기술은 인문학적 이해와 기술적 접근이 결합되어야 합니다.

```
2026-09-11 11:15:40
저녁반에 있었던 일인데 나이가 조금 있으신 분이 수업이 끝났는데 앞에 오셔서 상담을 요청하였음

그분도 교수님이셨음 (국어 국문학과)

요즘 ai가 너무 핫해서 국어 국문학과이지만 ai의 언어를 이용해서 연구 및 사업을 해보고 싶으시다고 하셨었음.

이야기를 나눠 봤는데 ai 에서 우리 (지금 2026-09-11 11:15:56의 허완은 완전 기초만 아는 정도이다.)

우리 회사에 신입이 들어온다면 최소 이정도는 알아야지 생각하면서 커리큘럼을 가르쳐주시고 계심.

분명히 그쪽 도메인 지식이 중요하다.

금융쪽 AI를 만든다고 한다면 금융쪽 직접 공부를 할 필요가 있음.
```

# 2. 자연어 처리
자연어 처리는(Natural Language Processing, NLP) 컴퓨터가 인간의 언어를 이해하고 처리하며 생성할 수 있도록 돕는 인공지능 기술 분야입니다.

이를 통해 텍스트나 음성 데이터를 분석하고, 번역, 요약, 감정 분석, 질의응답, 음성인식 등 다양한 작업을 수행할 수 있습니다.

자연어 처리는 언어학, 컴퓨터 과학, 인공지능의 융합으로 이루어지며, 형태소 분석, 구문 분석, 의미 분석 등 여러 단계를 포함합니다.

최근에는 딥러닝 기술과 대규모 언어 모델의 발전으로 자연어 처리 성능이 크게 향상되어 챗봇, 검색 엔진, 추천 시스템과 같은 실생활 응용에서 널리 사용되고 있습니다.

- 텍스트 분류
- 감정 분석
- 문서 관련 요약
- 기계 번역
- 질의 응답
- 정보 검색
- 챗봇
- 문장 생성
- RAG
- 전체 LLM 기반 Agent

> 최근에는 자연어 처리 기술이 이미지, 음성, 영상 등의 데이터와 결합하면서 Multimodal AI 확장

# **3. Corpus와 Document**

- Corpus(말뭉치)는 자연어 처리에서 분석하거나 학습하기 위해 수집한 전체 텍스트 데이터의 집합
- Document라고 해서 반드시 긴 문서를 의미하는 것은 아님
- 예) 뉴스기사 하나, 리뷰 하나, 댓글 하나, 문장 하나 등

# **3. Tokenization**
- 텍스트를 모델이 처리할 수 있는 작은 단위인 Token으로 나누는 과정
- [토큰 계산](https://platform.openai.com/tokenizer)

### 토큰
- 토큰은 모델이 처리하는 텍스트의 작은 단위
- 하나의 토큰은 단어, 부분적인 단어, 또는 공백이나 구두점일 수 있음
- 토큰은 반드시 단어 하나를 의미하지는 않음

### Vocabulary
- Vocabulary는 Tokenizer가 사용하는 Token들의 집합을 의미함
- 각 토큰에는 고유한 정수 ID가 할당됨
- 정수 ID 자체는 언어적인 의미가 전혀 없음

### 허길 페이스
허깅 페이스(Huffing Face)는 자연어 처리 뿐 아니라 이미지, 음성, 영상, 멀티모달 모델을 공유하고 사용하는 데 필요한 도구와 서비스를 제공하는 AI 생태계이자 회사 이름

In [1]:
import torch

print(torch.__version__)

2.14.0+cu130

In [2]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
elif torch.backends.mps.is_available():
    DEVICE = torch.device('mps')
elif torch.xpu.is_available():
    DEVICE = torch.device('xpu')
else:
    DEVICE = torch.device('cpu')

print(DEVICE)

cuda

In [3]:
text = "나는 자연어를 공부한다"
tokens = text.split(" ")

# tokens
vocab = {"<PAD>": 0, "<UNK>": 1, "나는:": 2, "자연어를": 3, "공부한다": 5}
token_ids = [vocab.get(token, vocab["<UNK>"]) for token in tokens]
token_ids

input_ids = torch.tensor(token_ids, dtype=torch.long)

In [4]:
print("원문: ", text)
print("Token: ", tokens)
print("Token ID: ", token_ids)
print("PyTorch Tensor: ", input_ids)
print("dtype: ", input_ids.dtype)

원문:  나는 자연어를 공부한다
Token:  ['나는', '자연어를', '공부한다']
Token ID:  [1, 3, 5]
PyTorch Tensor:  tensor([1, 3, 5])
dtype:  torch.int64

In [5]:
# 허깅페이스에서 제공하는 모듈
from transformers import AutoTokenizer

In [6]:
# 허깅페이스의 허브의 토큰 설정과 vocabulary를 가져오는 허브
# bert는 무언가가 있는 것이다.
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

딥러닝, CNN 류의 모든 연산이 뭔지 이미지를 파악하기 위해서, 데이터를 학습시키기 위해서 행렬 연산을 함.

행렬 연산은 사이즈가 맞아야함. 자연어도 행렬 연산을 해야하는데 사이즈가 맞아야만 함

사이즈를 넘기게 되면 다음번으로 넘기게 됨. (일정 량 이 상의 크기를 token을 하지 않고, 크기가 작으면 <PAD>를 넣어주는 방식을 사용함)

vocabulary에 스페셜 토큰이 존재함. (PAD: 크기 키우기용, UNK: unknown)

In [7]:
tokenizer

BertTokenizer(name_or_path='klue/bert-base', vocab_size=32000, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [8]:

tokens = tokenizer.tokenize(text)
print("Token:", tokens)
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print("token ID:", token_ids)

Token: ['나', '##는', '자연', '##어', '##를', '공부', '##한다']
token ID: [717, 2259, 3941, 2051, 2138, 4244, 4538]

In [9]:
print("Vocabulary 크기: ", tokenizer.vocab_size)
print("[PAD] ID: ", tokenizer.pad_token_type_id)
print("[UNK] ID: ", tokenizer.unk_token_id)
print("[CLS] ID: ", tokenizer.cls_token_id)
print("[SEP] ID: ", tokenizer.sep_token_id)

Vocabulary 크기:  32000
[PAD] ID:  0
[UNK] ID:  1
[CLS] ID:  2
[SEP] ID:  3

### OOV
- OOV(Out-Of-Vocabulary)는 Voca에 존재하지 않는 Token이 입력되는 문제
- 과거의 단어 단위 Voca에서는 처음보는 단어를 \<UNK\>와 같은 Unknown Token으로 처리하는 경우 가 많았음
- 현재 NLP에서는 Subword Tokenization을 이용하여 이 문제를 크게 줄임

In [10]:
vocab = {"<PAD>": 0, "<UNK>": 1, "나는:": 2, "파이토치를": 3, "공부한다": 5}
tokens = {"나는", "트랜스포머를", "공부한다"}

### Token ID
Tokenization이 끝나면 각각의 Token을 Vocabulary에 정의된 정수 ID로 변환
```
"오늘 날씨가 좋다" > Tokenization > [Token1, Token2, Token3. ...] > Token ID > [101, 205, 421, 23, ...]
```

m### Padding

- 문장은 각각 길이가 다름
- **Tensor**의 크기를 맞추기 위해 짧은 `Sequence`에 특별한 Padding Token을 추가하게 됨.

```python
문장 1 [15, 23, 51]
문장 2 [83, 12, 94, 21, 55]

▼ ▼ Padding 후 ▼ ▼
문장 1 [15, 23, 51, 0 , 0 ]
문장 2 [83, 12, 94, 21, 55]
```

> 일반적으로 0을 `<PAD>`의 ID로 사용
>

In [11]:
from torch.nn.utils.rnn import pad_sequence

# 문장 텐서
sentence1 = torch.tensor([15, 23, 51], dtype=torch.long)
sentence2 = torch.tensor([83, 12, 94, 21, 55], dtype=torch.long)
padded = pad_sequence(
    [sentence1, sentence2],
    padding_value=0,
    batch_first=True # 문장을 batch 형식대로 다시 만들어줌 (이렇게 하지 않으면 token 배열이 열에 나열되게 됨)b
)
print(padded, "\n", padded.shape)

tensor([[15, 23, 51,  0,  0],
        [83, 12, 94, 21, 55]])
 torch.Size([2, 5])

In [12]:
input_ids = torch.tensor([
    [15, 23, 51,  0,  0],
    [83, 12, 94, 21, 55]
], dtype=torch.long)

attention_mask = (input_ids != 0).long()
attention_mask

tensor([[1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1]])

# **4. 벡터화**
벡터화는 텍스트 데이터를 숫자 형태로 변환하여 머신러닝 또는 딥러닝 모델에서 처리할 수 있도록 만드는 과정입니다. 이를 위해 단어의 빈도를 기반으로 한 Bag-of-Words(BOW), TF-IDF와 같은 방법부터, 단어 간의 의미적 관계를 학습하는 Word Embedding(단어 임베딩), 문장의 문맥과 구조를 반영하는 Transformer 기반 임베딩(BERT, GPT) 등 다양한 기법이 사용됩니다. 벡터화는 단어, 문장, 문서와 같은 텍스트 데이터의 특징을 수치적으로 표현하며, 단순히 단어의 빈도를 반영하거나 의미적 유사성을 학습하여 벡터 공간에서 단어 간 관계를 나타냅니다. 데이터의 특성과 분석 목적에 따라 적절한 벡터화 기법을 선택하는 것이 중요합니다.

In [13]:
import torch.nn.functional as F

token_id = torch.tensor([2, 2, 2, 1, 3, 4], dtype=torch.long)
vocab_size = 5
one_hot = F.one_hot(token_id, num_classes=vocab_size)

token_id, one_hot

(tensor([2, 2, 2, 1, 3, 4]),
 tensor([[0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0],
         [0, 0, 0, 1, 0],
         [0, 0, 0, 0, 1]]))

In [14]:
import torch.nn as nn

In [15]:
# num_embeddings: vocabulary 크기
# embedding_dim: Token 하나를 표현할 Vector의 차원
# padding_idx: PADDING TOKEN의 idx가 어떤 것인지 (사용하는 vocab를 이용)
embedding = nn.Embedding(num_embeddings=100_000, embedding_dim=128, padding_idx=0)
print(embedding)
print(embedding.weight.shape)

Embedding(100000, 128, padding_idx=0)
torch.Size([100000, 128])

In [16]:
input_ids = torch.tensor([
    [1, 2, 3],
    [4, 2, 5]
], dtype=torch.long)

embedding=nn.Embedding(num_embeddings=10, embedding_dim=4, padding_idx=0)
output = embedding(input_ids)
print("입력 shape:", input_ids.shape)
print("출력 shape:", output.shape)
print("학습 여부:", embedding.weight.requires_grad)
print("Parameters 수:", embedding.weight.numel())
output

입력 shape: torch.Size([2, 3])
출력 shape: torch.Size([2, 3, 4])
학습 여부: True
Parameters 수: 40

tensor([[[ 1.3575, -0.1437, -0.1883, -0.8537],
         [-0.1160,  0.6006,  0.6027,  0.3738],
         [-2.2189, -0.8197, -0.8225,  0.3787]],

        [[ 0.0338, -0.6757, -0.1704,  0.1817],
         [-0.1160,  0.6006,  0.6027,  0.3738],
         [ 0.3596,  0.6173,  0.9787, -0.2118]]], grad_fn=<EmbeddingBackward0>)

In [17]:
from mecab import MeCab

In [18]:
from mecab import MeCab
mecab = MeCab()
mecab.morphs("아버지가방에들어가신다")

['아버지', '가', '방', '에', '들어가', '신다']

In [19]:
result = mecab.pos("아버지가방에들어가신다")
for morph, tag in result:
    print(morph, tag)

아버지 NNG
가 JKS
방 NNG
에 JKB
들어가 VV
신다 EP+EC

In [20]:
import urllib
# NSMC 데이터셋: 네이버 영화 리뷰를 기반으로 구축된 한국어 감성 분석 데이터셋
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings.txt", filename="ratings.txt")

('ratings.txt', <http.client.HTTPMessage at 0x1cb0048cd10>)

In [21]:
import pandas as pd
train_data = pd.read_table("ratings.txt")
# 리뷰 긍정은 1, 부정은 0
train_data[train_data["label"] == 0][:5], train_data[train_data["label"] == 1][:5]

(             id                     document  label
 100000  6826470           이런영화로 관객들한테 돈벌고싶소?      0
 100001  6239594  작품 선구안이 없다는게 배우 김태희의 최대 약점.      0
 100002  8946612              사극?? 로멘스?? 퓨젼??      0
 100003  4800899    ㅋㅋㅋㅋ엿국니네가그렇지므ㅝ 이건뭐 영화도아니고      0
 100004  5927640              완죤유치하고 못봐주겠네...      0,
          id                                           document  label
 0   8112052                                어릴때보고 지금다시봐도 재밌어요ㅋㅋ      1
 1   8132799  디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산...      1
 2   4655635               폴리스스토리 시리즈는 1부터 뉴까지 버릴께 하나도 없음.. 최고.      1
 3   9251303  와.. 연기가 진짜 개쩔구나.. 지루할거라고 생각했는데 몰입해서 봤다.. 그래 이런...      1
 4  10067386                        안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화.      1)

# 불용어
사용하지 않을 단어는 빼는 것을 불용어라고 부름m

In [22]:
train_data = train_data[:20000]

In [23]:
# 샘플 불용어 리스트
stopwords = ['도', '는', '다', '의', '가', '이', '은', '한', '에', '하', '고', '을', '를', '인', '듯', '과', '와', '네', '들', '듯', '지', '임', '게']

In [24]:
# train_data["document"] = train_data["document"].str.replace('[^ㄱ-ㅎㅏ-ㅣ가-힣]', '', regex=True)
train_data['document'] = train_data['document'].str.replace('[^ㄱ-ㅎㅏ-ㅣ가-힣 ]', '', regex=True)

train_data[:5]

         id                                           document  label
0   8112052                                어릴때보고 지금다시봐도 재밌어요ㅋㅋ      1
1   8132799  디자인을 배우는 학생으로 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업...      1
2   4655635                   폴리스스토리 시리즈는 부터 뉴까지 버릴께 하나도 없음 최고      1
3   9251303   와 연기가 진짜 개쩔구나 지루할거라고 생각했는데 몰입해서 봤다 그래 이런게 진짜 영화지      1
4  10067386                         안개 자욱한 밤하늘에 떠 있는 초승달 같은 영화      1

In [25]:
train_data["document"].dtype

In [26]:
macab = MeCab()
tokenized_data = []

for sentence in train_data["document"]:
    tempX = mecab.morphs(sentence)
    tempX = [
        word
        for word in tempX
        if not word in stopwords
    ]

    tokenized_data.append(tempX)

In [27]:
len(tokenized_data)

20000

In [28]:
import gensim
gensim.__version__

'4.4.0'

In [29]:
from gensim.models import Word2Vec

In [30]:
# sentences: 학습에 사용할 문장 데이터
# vector_size: 벡터 표현
# window: 주변 단어를 몇 개 볼 것인지
# min_count: 몇 번 이상 등장한 단어만 학습에 포함
# workers: CPU 코어 사용 개수
# sg: CBOW(0), Skip-gram(1)
# negative: Negative Sampling에서 사용할 음성 샘플 개수
model = Word2Vec(
    sentences=tokenized_data,
    vector_size=100,
    window=5,
    min_count=5,
    workers=2,
        sg=1,
    negative=5
)

In [31]:
model.wv.vectors.shape

(3997, 100)

In [32]:
# Word2Vec이 학습한 단어 중에서 의미적으로 비슷하게 사용된 단어를 찾아줌
# wv: 학습된 단어 벡터들을 관리
# 결과는 코사인 유사도 > 1에 가까울수록 두 단어의 벡터 방향이 비슷함
model.wv.most_similar("블록버스터", topn=5)

[('미스테리', 0.9856197834014893),
 ('정상', 0.9832184314727783),
 ('일거', 0.9830852746963501),
 ('시인', 0.9820321798324585),
 ('견자단', 0.9818759560585022)]

In [33]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/bab2min/corpus/master/sentiment/naver_shopping.txt", filename="ratings_total.txt")

('ratings_total.txt', <http.client.HTTPMessage at 0x1cb0a260d10>)

In [34]:
total_data = pd.read_table("ratings_total.txt", names=["ratings", "reviews"])
total_data.head()

   ratings                                            reviews
0        5                                            배공빠르고 굿
1        2                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
2        5  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
3        2  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
4        5                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ

In [35]:
len(total_data)

200000

In [36]:
import hgtk 

def morpheme_forward(text: str):
    morphs = mecab.morphs(text)
    result = []

    for morph in morphs:
        str_build = ""
        # print("형태소 하나:", morph)

        # 형태소가 2단어 이상일 경우에 분해해서 구해야함.
        for m in morph:
            # print("\t단어 하나:",m)
            # print("m:", m)
            if hgtk.checker.is_hangul(m):
                append_elem = hgtk.letter.decompose(m)
                # 받힘이 없으면 `-` 추가해주기
                # print(append_elem)
                if append_elem[2] == "":
                    append_elem = append_elem[:2] + tuple("-")
                # print("\t\t단어 분해:", append_elem)
                str_build += "".join(append_elem)
            else:
                # 특수기호나 영어는 통과
                str_build += m
        # print(str_build)

        result.append(str_build)

    print(result)

In [37]:
from hgtk.exception import NotHangulException

def word_to_jamo(token):
  def to_special_token(jamo):
    if not jamo:
      return "-"
    else:
      return jamo

  decomposed_token = ""

  for char in token:
    try:
      cho, jung, jong = hgtk.letter.decompose(char)
      cho = to_special_token(cho)
      jung = to_special_token(jung)
      jong = to_special_token(jong)

      decomposed_token = decomposed_token + cho + jung + jong
    except NotHangulException as e:
      decomposed_token += char
    except Exception as e:
      print(e)

  return decomposed_token

In [38]:
word_to_jamo("나는 school에 갔다")

'ㄴㅏ-ㄴㅡㄴ schoolㅇㅔ- ㄱㅏㅆㄷㅏ-'

In [39]:
mecab.morphs("선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다.")

['선물',
 '용',
 '으로',
 '빨리',
 '받',
 '아서',
 '전달',
 '했어야',
 '하',
 '는',
 '상품',
 '이',
 '었',
 '는데',
 '머그',
 '컵',
 '만',
 '와서',
 '당황',
 '했',
 '습니다',
 '.']

In [40]:
def tokenize_by_jamo(s):
  """문장을 받아서 형태소를 분석해서 초중종성으로 나눠서 리스트로 만들어줌"""
  return [word_to_jamo(token) for token in mecab.morphs(s)]

In [41]:
tokenize_by_jamo("나는 오늘 'school'에 갔습니다.")

['ㄴㅏ-', 'ㄴㅡㄴ', 'ㅇㅗ-ㄴㅡㄹ', "'", 'school', "'", 'ㅇㅔ-', 'ㄱㅏㅆ', 'ㅅㅡㅂㄴㅣ-ㄷㅏ-', '.']

In [42]:
from tqdm import tqdm

In [43]:
tokenized_data = []

for sample in tqdm(total_data["reviews"].to_list()):
  tokenized_sample = tokenize_by_jamo(sample)
  
  tokenized_data.append(tokenized_sample)

100%|██████████| 200000/200000 [01:00<00:00, 3329.00it/s]

In [44]:
tokenized_data[0]

['ㅂㅐ-ㄱㅗㅇ', 'ㅃㅏ-ㄹㅡ-', 'ㄱㅗ-', 'ㄱㅜㅅ']

In [45]:
def jamo_to_word(jamo_sequence):
  tokenized_jamo = []

  index = 0

  while index < len(jamo_sequence):
    if not hgtk.checker.is_hangul(jamo_sequence[index]):
      tokenized_jamo.append(jamo_sequence[index])
      index = index + 1
    else:
      tokenized_jamo.append(jamo_sequence[index:index+3])
      index = index + 3

  word = ""
  try:
    for jamo in tokenized_jamo:
      if len(jamo) == 3:
        if jamo[2] == '-':
          word = word + hgtk.letter.compose(jamo[0], jamo[1])
        else:
          word = word + hgtk.letter.compose(jamo[0], jamo[1], jamo[2])
      else:
        word = word + jamo
  
  except NotHangulException as e:
    return jamo_sequence

  return word

In [46]:
jamo_to_word("ㅅㅓㄴㅁㅜㄹ ㅇㅡㄹ ㅂㅏㄷㅇㅏㅆㅅㅡㅂㄴㅣ-ㄷㅏ- .")

'선물 을 받았습니다 .'

In [47]:
jamo_to_word("ㄱㅟ-ㅇㅝ-")
jamo_to_word("ㅇㅕ-ㅁㅁㅜㄹaa")

'ㅇㅕ-ㅁㅁㅜㄹaa'

In [48]:
with open("tokenized_data.txt", "w", encoding="utf_8") as out:
  for line in tqdm(tokenized_data, unit="line"):
    out.write(" ".join(line) + "\n")

  0%|          | 0/200000 [00:00<?, ?line/s]

100%|██████████| 200000/200000 [00:00<00:00, 233254.23line/s]

In [49]:
import fasttext

model = fasttext.train_unsupervised('tokenized_data.txt', model='cbow')
model.save_model('fasttext.bin')

In [52]:
# 100차원짜리 token vector
model[word_to_jamo('남동생')].shape, model[word_to_jamo('남동생')]

((100,),
 array([ 0.07184339,  0.7969706 ,  0.03586473, -0.1480508 ,  0.42769387,
         0.32337156, -0.3256299 ,  0.13658336, -0.44362932, -0.2654678 ,
         0.17776337,  0.267747  , -0.34600517, -0.2963728 , -0.14141905,
        -0.2103679 ,  0.5648214 , -0.20663296,  1.458878  , -0.365305  ,
        -0.32354027,  0.39944327, -0.17963025, -0.6411398 , -0.30783767,
         0.21278627,  0.19823243, -1.5704448 , -0.36752066,  0.09683762,
        -0.4973191 ,  0.16890053,  0.3932307 , -1.6101092 , -0.17971233,
         0.2723677 , -0.8547582 ,  0.34731454, -0.28053388,  0.04093627,
        -0.6166666 ,  0.9332729 , -0.04044859,  0.23357233, -0.48465696,
        -0.5746063 ,  0.17864355,  0.5700513 , -0.02669604,  0.72043496,
         0.49781692,  1.0051627 , -1.0035633 ,  0.29176188,  0.47247586,
         1.209413  , -0.21946551, -0.14604007, -0.66529095,  0.91023225,
        -0.4584984 , -0.11699668,  0.5782668 ,  1.1488192 ,  0.02806575,
         0.60420245,  0.29009873, -0.69251364,  0.2627007 , -0.11673601,
         0.1617104 ,  0.28855968, -0.15908672, -0.6108989 , -0.24896058,
         0.15142871,  1.1156378 ,  0.12349986,  0.33001196,  1.0753992 ,
        -0.80523854, -0.0115278 ,  0.13224675,  0.8596319 ,  0.43429706,
        -0.3277878 ,  0.70652217, -1.0818706 ,  0.08679426, -0.02401377,
        -0.5173016 , -0.260963  , -1.0410769 ,  0.47406676,  0.16231564,
         0.21106012,  0.56782717, -0.3436448 , -0.5113582 , -0.12323247],
       dtype=float32))

In [ ]:
model.get_nearest_neighbors(word_to_jamo('남동생'), k=10)

[(0.8859543800354004, 'ㄷㅗㅇㅅㅐㅇ'),
 (0.8407570719718933, 'ㄴㅏㅁㅊㅣㄴ'),
 (0.7403780817985535, 'ㅅㅐㅇㅇㅣㄹ'),
 (0.7340975403785706, 'ㄴㅏㅁㅍㅕㄴ'),
 (0.7153514623641968, 'ㅊㅣㄴㄱㅜ-'),
 (0.7125493884086609, 'ㄴㅏㅁㅇㅏ-'),
 (0.7007817029953003, 'ㅈㅜㅇㅎㅏㄱㅅㅐㅇ'),
 (0.6883882880210876, 'ㅈㅗ-ㅋㅏ-'),
 (0.6875677704811096, 'ㅅㅓㄴㅁㅜㄹ'),
 (0.6873489618301392, 'ㄴㅏㄴㅅㅐㅇ')]

In [ ]:
def transform(word_sequence):
    return [(jamo_to_word(word), similarity) for (similarity, word) in word_sequence]
# print(transform(model.get_nearest_neighbors(word_to_jamo('남동생'), k=10)))
# print(transform(model.get_nearest_neighbors(word_to_jamo('남동쉥'), k=10)))
# print(transform(model.get_nearest_neighbors(word_to_jamo('남동셍ㅋ'), k=10)))
print(transform(model.get_nearest_neighbors(word_to_jamo('난동생'), k=10)))
print(transform(model.get_nearest_neighbors(word_to_jamo('낫동생'), k=10)))

def transform(word_sequence):
    return [((word), similarity) for (similarity, word) in word_sequence]
# print(transform(model.get_nearest_neighbors(word_to_jamo('납동생'), k=10)))
# print(transform(model.get_nearest_neighbors(word_to_jamo('냚동생'), k=10)))
print(transform(model.get_nearest_neighbors(word_to_jamo('제품^^'), k=10)))
print(transform(model.get_nearest_neighbors(word_to_jamo('남짓'), k=10)))

[('남동생', 0.862177848815918), ('난생', 0.8400022983551025), ('동생', 0.7805193066596985), ('남편', 0.7660334706306458), ('남친', 0.7547032833099365), ('남아', 0.7522525191307068), ('중학생', 0.7030736804008484), ('남매', 0.6843194961547852), ('동남아', 0.6707218289375305), ('고등학생', 0.668799102306366)]
[('남동생', 0.9271200299263), ('동생', 0.8868505358695984), ('남친', 0.755257248878479), ('중학생', 0.7360196113586426), ('난생', 0.7357205748558044), ('남편', 0.728854238986969), ('남아', 0.6955615282058716), ('학생', 0.6952959895133972), ('조카', 0.6874977350234985), ('친구', 0.6851798295974731)]
[('ㅈㅔ-ㅍㅜㅁ', 0.9347923398017883), ('ㅈㅔ-ㅍㅜㅇ', 0.806834876537323), ('ㅅㅏㅇㅍㅜㅁ', 0.7672395706176758), ('ㅂㅏㄴㅈㅔ-ㅍㅜㅁ', 0.7595667243003845), ('ㅌㅏ-ㅈㅔ-ㅍㅜㅁ', 0.7470489740371704), ('ㅊㅚ-ㅅㅏㅇㅍㅜㅁ', 0.7410162687301636), ('ㅇㅘㄴㅈㅔ-ㅍㅜㅁ', 0.7384857535362244), ('ㅈㅐ-ㅍㅜㅁ', 0.7103825807571411), ('ㅎㅘ-ㅎㅏㄱㅈㅔ-ㅍㅜㅁ', 0.6855525374412537), ('ㅈㅜㅇㅍㅜㅁ', 0.6776936650276184)]
[('ㄴㅏㅁㅇㅡㅁ', 0.8459800481796265), ('ㄴㅏㅁ', 0.8090157508850098), ('ㄴㅏㅁㄴㅕ-', 0.807458221912384), ('ㄴㅏㅁㅇㅕ-', 0.787817120552063), ('ㄴㅏㅁㅈㅏ-', 0.7635770440101624), ('ㄴㅏㅁㅁㅐ-', 0.7584300637245178), ('ㄴㅏㅁㅇㅏ-', 0.7543670535087585), ('ㄴㅏㅁㅊㅣㄴ', 0.723754346370697), ('ㄴㅏㅁㅇㅏ-ㄷㅗㄹ', 0.7234501838684082), ('ㄴㅏㅁㄱㅣㄴ', 0.6762829422950745)]

In [ ]:
word = "대한민국"
subwords, indices = model.get_subwords(word)
subwords, indices

(['<대한',
  '<대한민',
  '<대한민국',
  '<대한민국>',
  '대한민',
  '대한민국',
  '대한민국>',
  '한민국',
  '한민국>',
  '민국>'],
 array([1217659,  900777, 1677261,  189815,  168755,  696735, 1367137,
         765176, 1621740, 1858624]))